name: Sync to Google Cloud Storage

on:
  push:
    branches:
      - main
    paths-ignore:
      - "images/origin/**"

jobs:
  sync-to-gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Cloud SDK
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Sync files to GCS
        run: |
          echo "Starting sync process..."

          # バケットが存在することを確認
          echo "Checking bucket..."
          if ! gsutil ls gs://cs_resources > /dev/null 2>&1; then
            echo "Error: Bucket gs://cs_resources does not exist"
            exit 1
          fi
          echo "Bucket exists."

          # 現在のリポジトリ内のファイルを確認（デバッグ用）
          echo "Files in repository:"
          find . -type f -not -path '*/\.*' -not -path '*/images/origin/*' -not -path './gha-creds-*.json'

          # 前回のコミットハッシュを取得
          PREVIOUS_COMMIT=$(git rev-parse HEAD^1 2>/dev/null || echo "initial")

          if [ "$PREVIOUS_COMMIT" = "initial" ]; then
            echo "Initial commit detected - uploading all files"
            # 初回コミット時は全ファイルをアップロード
            find . -type f -not -path '*/\.*' -not -path '*/images/origin/*' -not -path './gha-creds-*.json' | while read file; do
              # ファイルパスから先頭の "./" を削除
              relative_path=${file#./}
              echo "Uploading: $relative_path"
              gsutil -m cp "$file" "gs://cs_resources/$relative_path"
            done
          else
            echo "Processing changes since previous commit"
            # 変更されたファイルの確認
            git diff --name-status $PREVIOUS_COMMIT HEAD | while read status file; do
              if [[ ! "$file" =~ ^images/origin/ ]] && [[ ! "$file" =~ ^\.git ]]; then
                case $status in
                  D)
                    echo "Deleting: $file"
                    gsutil rm "gs://cs_resources/$file" || true
                    ;;
                  A|M)
                    if [ -f "$file" ]; then
                      echo "Uploading: $file"
                      gsutil -m cp "$file" "gs://cs_resources/$file"
                    fi
                    ;;
                esac
              fi
            done
          fi

          echo "Sync process completed."
