name: Sync to Google Cloud Storage

on:
  push:
    branches:
      - main
    paths-ignore:
      - "images/origin/**"

jobs:
  sync-to-gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Cloud SDK
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Verify GCP Setup
        id: verify
        run: |
          echo "Verifying GCP setup..."

          # 認証状態の確認
          if ! gcloud auth list 2>&1 | grep -q "Credentialed Accounts"; then
            echo "Error: GCP authentication failed"
            exit 1
          fi

          # プロジェクトの確認
          PROJECT=$(gcloud config get-value project)
          if [ -z "$PROJECT" ]; then
            echo "Error: No GCP project set"
            exit 1
          fi
          echo "Using GCP Project: $PROJECT"

          # バケットの確認
          if ! gsutil ls gs://cs_resources > /dev/null 2>&1; then
            echo "Error: Cannot access bucket gs://cs_resources"
            exit 1
          fi
          echo "Successfully verified GCP setup"

      - name: Upload to GCS
        run: |
          echo "Starting upload process..."

          # アップロード対象ファイルの確認
          FILES_TO_UPLOAD=$(find . -type f \
            -not -path '*/\.*' \
            -not -path '*/images/origin/*' \
            -not -path './gha-creds-*.json')

          if [ -z "$FILES_TO_UPLOAD" ]; then
            echo "Error: No files found to upload"
            exit 1
          fi

          # ファイル数をカウント
          FILE_COUNT=$(echo "$FILES_TO_UPLOAD" | wc -l)
          echo "Found $FILE_COUNT files to upload"

          # アップロード処理
          FAILED_UPLOADS=0
          while IFS= read -r file; do
            relative_path=${file#./}
            echo "Uploading: $relative_path to gs://cs_resources/$relative_path"
            if ! gsutil -m cp "$file" "gs://cs_resources/$relative_path"; then
              echo "Error: Failed to upload $relative_path"
              FAILED_UPLOADS=$((FAILED_UPLOADS + 1))
            fi
          done <<< "$FILES_TO_UPLOAD"

          # 結果の確認
          if [ $FAILED_UPLOADS -gt 0 ]; then
            echo "Error: $FAILED_UPLOADS files failed to upload"
            exit 1
          fi

          echo "Upload process completed successfully"
          echo "Verifying uploaded files:"
          gsutil ls -r gs://cs_resources/
